SOLGAMEUI = {
    'CASE_STATUS' : {}
};


SOLGAMEUI.CASE_STATUS[SOLCORE.Case.TypeEnum.EMPTY] = '.';
SOLGAMEUI.CASE_STATUS[SOLCORE.Case.TypeEnum.FORBIDDEN] = '';
SOLGAMEUI.CASE_STATUS[SOLCORE.Case.TypeEnum.FULL] = 'O';